#!/bin/bash

# Script to update project overview with email extraction results
OVERVIEW_FILE="/Users/simonwang/Documents/Usage/ObSync/Vault4sync/project overview and progress.md"
DATE=$(date "+%Y-%m-%d")

echo "" >> "$OVERVIEW_FILE"
echo "#### Email Information Extraction - $DATE:" >> "$OVERVIEW_FILE"
echo "**Source**: Technical team discussion email from August 10, 2025" >> "$OVERVIEW_FILE"
echo "" >> "$OVERVIEW_FILE"
echo "**Key Contacts Added**:" >> "$OVERVIEW_FILE"
echo "- Simon H WANG (simonwang@hkbu.edu.hk) - Project Lead" >> "$OVERVIEW_FILE"
echo "- Zian ZHENG/Kaitai Zhang (22231153@life.hkbu.edu.hk) - Technical Developer" >> "$OVERVIEW_FILE"
echo "- Andy (21253153@life.hkbu.edu.hk) - Technical Developer" >> "$OVERVIEW_FILE"
echo "- Yuen Yi LAW (ellielaw@hkbu.edu.hk) - Team Member" >> "$OVERVIEW_FILE"
echo "- John DELLA PIETRA (johndp@hkbu.edu.hk) - Team Member" >> "$OVERVIEW_FILE"
echo "- Cissy Y X LI (yxli@hkbu.edu.hk) - Team Member" >> "$OVERVIEW_FILE"
echo "" >> "$OVERVIEW_FILE"
echo "**Platform Information Discovered**:" >> "$OVERVIEW_FILE"
echo "- Avatar Management: https://chat.hkbu.life/#/teacher/manage-avatars" >> "$OVERVIEW_FILE"
echo "- Current Avatar: ChineseMedTutor" >> "$OVERVIEW_FILE"
echo "- Demo Video: https://meeting.tencent.com/cw/295QPG5q2d" >> "$OVERVIEW_FILE"
echo "- Integration Target: https://gamesbe.asia:3000/GamePlay/Clinical_handover" >> "$OVERVIEW_FILE"
echo "" >> "$OVERVIEW_FILE"
echo "**August 2025 Requirements Identified**:" >> "$OVERVIEW_FILE"
echo "1. Multiple avatar selection and voices" >> "$OVERVIEW_FILE"
echo "2. Conversation transcript management" >> "$OVERVIEW_FILE"
echo "3. HTML web page embedding with SSO" >> "$OVERVIEW_FILE"
echo "4. AI-powered report generation from transcripts" >> "$OVERVIEW_FILE"
echo "5. Dialogue video generation capability" >> "$OVERVIEW_FILE"
echo "" >> "$OVERVIEW_FILE"
echo "**Files Updated**:" >> "$OVERVIEW_FILE"
echo "- contacts/contacts.json - Added 6 team member contacts" >> "$OVERVIEW_FILE"
echo "- README.md - Added platform and integration information" >> "$OVERVIEW_FILE"
echo "- docs/august-2025-requirements.md - Documented development requirements" >> "$OVERVIEW_FILE"
echo "- contacts/demo_schedule.md - Updated with active development status" >> "$OVERVIEW_FILE"
echo "" >> "$OVERVIEW_FILE"

echo "✅ Email extraction results added to project overview"
echo "📧 6 contacts added to contact management system"
echo "📋 August 2025 requirements documented"
echo "📅 Updated: $DATE"